day 6 factorial
==== RESTART: C:/Users/DELL/AppData/Local/Programs/Python/Python39/exp 2.py ====
Enter a number: 0
The factorial of 0 is 1
>>> 
= RESTART: C:/Users/DELL/AppData/Local/Programs/Python/Python39/exp 2.py
Enter a number: -5
Sorry, factorial does not exist for negative numbers
>>> 
= RESTART: C:/Users/DELL/AppData/Local/Programs/Python/Python39/exp 2.py
Enter a number: 1
The factorial of 1 is 1
>>> 
= RESTART: C:/Users/DELL/AppData/Local/Programs/Python/Python39/exp 2.py
Enter a number: 20
The factorial of 20 is 2432902008176640000
>>> 
= RESTART: C:/Users/DELL/AppData/Local/Programs/Python/Python39/exp 2.py
Enter a number: 3A
Traceback (most recent call last):
  File "C:/Users/DELL/AppData/Local/Programs/Python/Python39/exp 2.py", line 1, in <module>
    num = int(input("Enter a number: "))
ValueError: invalid literal for int() with base 10: '3A'
>>>